Fix issue in teardown when cleanup_after is used
Fix error
"File "tests/base.py", line 121, in tearDown
   os.remove(file)
OSError: [Errno 21] Is a directory:"
that has occured in teardown when OS_CLEANUP_AFTER is TRUE

Change-Id: I9c3ad125b7c9034fe6f6bab7a0dae1acbe15289a